# Generated by Django 3.1.2 on 2020-12-09 11:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0002_auto_20201206_1407'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='price',
            field=models.IntegerField(default=5000, verbose_name='Цена'),
            preserve_default=False,
        ),
    ]
