# Generated by Django 3.1.2 on 2020-12-09 21:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0003_product_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='is_contract_price',
            field=models.BooleanField(default=False, verbose_name='Договорная цена'),
        ),
        migrations.AddField(
            model_name='product',
            name='sale_price',
            field=models.IntegerField(blank=True, default=0, verbose_name='Цена'),
            preserve_default=False,
        ),
    ]
