# Generated by Django 3.1.2 on 2020-12-12 10:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0006_auto_20201210_2258'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='sale_price',
            field=models.IntegerField(blank=True, default=0, null=True, verbose_name='Цена по скидке'),
        ),
    ]
