# Generated by Django 3.1.2 on 2020-12-13 15:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0007_auto_20201212_1352'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='img',
        ),
        migrations.AddField(
            model_name='product',
            name='img_1',
            field=models.ImageField(default=0, upload_to='Products', verbose_name='Фотография №1*'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='product',
            name='img_2',
            field=models.ImageField(null=True, upload_to='Products', verbose_name='Фотография №2'),
        ),
        migrations.AddField(
            model_name='product',
            name='img_3',
            field=models.ImageField(null=True, upload_to='Products', verbose_name='Фотография №3'),
        ),
        migrations.AddField(
            model_name='product',
            name='img_4',
            field=models.ImageField(null=True, upload_to='Products', verbose_name='Фотография №4'),
        ),
        migrations.AddField(
            model_name='product',
            name='img_5',
            field=models.ImageField(null=True, upload_to='Products', verbose_name='Фотография №5'),
        ),
        migrations.AlterField(
            model_name='category',
            name='name',
            field=models.CharField(max_length=100, verbose_name='Название*'),
        ),
        migrations.AlterField(
            model_name='product',
            name='description',
            field=models.TextField(max_length=1000, verbose_name='Описание*'),
        ),
        migrations.AlterField(
            model_name='product',
            name='name',
            field=models.CharField(max_length=100, verbose_name='Название*'),
        ),
        migrations.AlterField(
            model_name='product',
            name='price',
            field=models.IntegerField(null=True, verbose_name='Цена*'),
        ),
    ]
