# Generated by Django 3.1.2 on 2020-12-26 20:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0008_auto_20201213_1835'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='products', to='main_app.category', verbose_name='Категория*'),
        ),
        migrations.AlterField(
            model_name='product',
            name='img_2',
            field=models.ImageField(blank=True, default='null', upload_to='Products', verbose_name='Фотография №2'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='product',
            name='img_3',
            field=models.ImageField(blank=True, default='null', upload_to='Products', verbose_name='Фотография №3'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='product',
            name='img_4',
            field=models.ImageField(blank=True, default='null', upload_to='Products', verbose_name='Фотография №4'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='product',
            name='img_5',
            field=models.ImageField(blank=True, default='null', upload_to='Products', verbose_name='Фотография №5'),
            preserve_default=False,
        ),
    ]
