# Generated by Django 3.1.2 on 2021-01-09 17:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0011_user'),
    ]

    operations = [
        migrations.DeleteModel(
            name='User',
        ),
    ]
