# Generated by Django 3.1.2 on 2021-01-10 08:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0013_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='phone_number',
            field=models.IntegerField(default=0, max_length=12, verbose_name='Номер телефона'),
            preserve_default=False,
        ),
    ]
