# Generated by Django 3.1.2 on 2021-01-10 08:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0015_auto_20210110_1142'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='order',
            options={'verbose_name': 'Заказ', 'verbose_name_plural': 'Заказы'},
        ),
        migrations.AddField(
            model_name='order',
            name='delivery_type',
            field=models.CharField(blank=True, choices=[('none', 'Статус отсутствует'), ('Самовывоз', 'Самовывоз'), ('СДЭК', 'СДЭК'), ('DHL', 'DHL')], default='none', max_length=64, verbose_name='Способ получения заказа'),
        ),
        migrations.AlterField(
            model_name='order',
            name='description',
            field=models.TextField(max_length=1000, verbose_name='Описание'),
        ),
    ]
