# Generated by Django 3.1.2 on 2021-01-10 09:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0016_auto_20210110_1150'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('В обработке', 'В обработке'), ('Выполнен', 'Выполнен'), ('Отменен', 'Отменен')], default='none', max_length=64, verbose_name='Способ получения заказа'),
        ),
        migrations.AlterField(
            model_name='order',
            name='delivery_type',
            field=models.CharField(choices=[('none', 'Статус отсутствует'), ('Самовывоз', 'Самовывоз'), ('СДЭК', 'СДЭК'), ('DHL', 'DHL')], default='none', max_length=64, verbose_name='Способ получения заказа'),
        ),
    ]
