# Generated by Django 3.1.2 on 2021-01-10 09:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0017_auto_20210110_1211'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('В обработке', 'В обработке'), ('Выполнен', 'Выполнен'), ('Отменен', 'Отменен')], default='В обработке', max_length=64, verbose_name='Статус заказа'),
        ),
    ]
