# Generated by Django 3.1.2 on 2021-01-10 12:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0018_auto_20210110_1211'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='img_mini',
        ),
        migrations.AlterField(
            model_name='order',
            name='delivery_type',
            field=models.CharField(choices=[('Самовывоз', 'Самовывоз'), ('СДЭК', 'СДЭК'), ('DHL', 'DHL')], default='none', max_length=64, verbose_name='Способ получения заказа'),
        ),
    ]
