# Generated by Django 3.1.2 on 2021-01-10 20:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0020_auto_20210110_1529'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='img_mini',
            field=models.ImageField(blank=True, null=True, upload_to='Products', verbose_name='Фотография №1 мини'),
        ),
    ]
